spring:
  application:
    name: eureka-server
#server:
#  port: 8082
#
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  cloud:
    uri: http://localhost:8081/
    user: develop
    password: develop